version: '3.1'

services:

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: userdb
      MONGO_INITDB_ROOT_PASSWORD: password123